---
title: "EDA"
author: "Bre'Aria, Sofia, and Adriana"
format: html
editor: source
---

## EDA

```{r}
library(ggplot2)
library(tidyverse)
library(RColorBrewer)
library(leaflet)
library(janitor)
library(readr)
```

```{r}
#read clean data
df <- read_csv("data/cleaned_salary_2024.csv")
View(df)
```


```{r}
#Function for summary table of by specific column
summary_by <-function(col_name){
  df |> 
  group_by(.data[[col_name]]) |> 
  summarise(
    mean_salary = mean(salary),
    median_salary = median(salary),
    n = n(),
    .groups = "drop"
  )
}
```

```{r}
exp_summary<- summary_by("experience_level")
```

```{r}
comp_summary<- summary_by("company_size")

```

```{r}
#function to plot salary with any categorical variable or numeric that can be made as a factor
salary_vs <-function(col_name){
  df|>
    mutate(across(all_of(col_name), as.factor))|>
    ggplot( aes_string(x=col_name, y ="salary" ))+
      geom_boxplot()+
      theme_minimal()+
      labs(title = paste("Salary by", col_name),
           x = col_name,
           y = "Salary (USD)")
}
```

```{r}
#Salary by Experience level
salary_vs("experience_level")
```

```{r}
#Salary by Company size

salary_vs("company_size")
```

```{r}
#Salary by Remote size

salary_vs("remote_ratio")

```


```{r}
df |>
ggplot(aes(x = remote_ratio,
           fill = experience_level)) +
         geom_bar(position = "dodge") +
  labs(x = "Remote Ratio",
       y = "Employee Count",
       fill = "Experience Level",
       title = "Distribution of Remote Data Developer Work Ratios by Experience Level in 2024",
       subtitle = "0.0 = In Person Job, 0.5 = Hybrid Job, 1.0 = Remote Job") +
  theme_bw() +
  scale_fill_brewer(palette = "GnBu") +
  scale_x_continuous(breaks = seq(0, 100, by = .5))
```

```{r}
df |>
ggplot(aes(x = remote_ratio)) +
  facet_wrap(vars(company_size)) +
  geom_histogram(binwidth = .5, 
                 color = "white",
                 fill = "Pink") +
  labs(x = "Remote Ratio",
       y = "Employee Count",
       title = "Remote Work Distribution by Company Size in 2024",
       subtitle = "0.0 = In Person Job, 0.5 = Hybrid Job, 1.0 = Remote Job") +
   theme_bw()
```
